# File: cleanup.py
#
# Contains the advanced in-memory cleanup logic for AsciiDoc content.
#
import re
import sys
import os


def cleanup_adoc_string(adoc_content_string, log_func=print):
    """
    Applies general cleanup and fixes to the generated AsciiDoc content (in-memory string),
    reversing the over-aggressive list insertion and fixing step attributes.
    """
    log_func("    Applying in-memory cleanup logic...")
    try:
        content = adoc_content_string

        # --- Structural Cleanup ---

        # 1. FIX: Remove isolated, empty AsciiDoc section headers (e.g., '== \n *')
        cleaned_content = re.sub(r"^\s*=+?\s*$", r"", content, flags=re.MULTILINE)

        # 2. FIX: Remove unwanted soft line breaks ('+') generated by Pandoc
        cleaned_content = re.sub(r",\s*\n\s*\+\s*\n", r",\n", cleaned_content)
        cleaned_content = re.sub(r"([^\n,])\n\s*\+\s*\n", r"\1\n", cleaned_content)
        cleaned_content = re.sub(
            r"(.+?)\s*\+\s*$", r"\1", cleaned_content, flags=re.MULTILINE
        )

        # --- FIX FAULT STEP SHORTCODES ---
        cleaned_content = re.sub(r"\+\+_\+\+", "_", cleaned_content)
        cleaned_content = re.sub(r"\+\+\[\+\[(.+?)\]\+\]\+\+", r"[\1]", cleaned_content)
        cleaned_content = re.sub(
            r'\[role="([^"]+)"\s*,\s*(.*?)\]', r"[.\1, \2]", cleaned_content
        )
        cleaned_content = re.sub(r'\[role="([^"]+)"\s*\]', r"[.\1]", cleaned_content)

        # --- FIX: Reversing over-aggressive list insertion (dots everywhere) ---
        cleaned_content = re.sub(
            r"^\s*\.(\=+)\s+", r"\1 ", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*\.(\[.+?\])", r"\1", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*\.\|===", r"|===", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"\[arabic(\s*,\s*start=\d+)?\]\s*",
            r"",
            cleaned_content,
            flags=re.MULTILINE,
        )
        cleaned_content = re.sub(
            r"^\s*\.\s*$\n([A-Z0-9\[].*)", r". \1", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*\.\s+Sub-step", r".. Sub-step", cleaned_content, flags=re.MULTILINE
        )

        # --- General Cleanup (Final pass for previously working fixes) ---
        cleaned_content = re.sub(
            r"\{\s*empty\s*\}", r"", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*\{plus\}\s*$", r"+", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*____\s*$", r"", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(r"(--\n)\s+", r"\1", cleaned_content)
        cleaned_content = re.sub(r"\s+(\n--)", r"\1", cleaned_content)

        # --- CROSS-REFERENCE FIXES (<<ref>>) ---
        cleaned_content = re.sub(r"<<\s*(.+?)\s*>>", r"<<\1>>", cleaned_content)
        cleaned_content = re.sub(
            r"<<(.*)([\.\,\?\!\:\;])>>", r"<<\1>>\2", cleaned_content
        )

        # FIX 4: Join multi-line attribute blocks `[...]` into a single line
        # (Omitting for brevity as it's unchanged - see previous full code)
        lines = cleaned_content.splitlines()
        rebuilt_lines = []
        in_attribute_block = False
        for line in lines:
            stripped_line = line.strip()
            if stripped_line.startswith("[") and not stripped_line.endswith("]"):
                in_attribute_block = True
                rebuilt_lines.append(line.rstrip())
            elif in_attribute_block:
                rebuilt_lines[-1] += " " + stripped_line.replace("`", "")
                if stripped_line.endswith("]"):
                    in_attribute_block = False
            else:
                rebuilt_lines.append(line)
        cleaned_content = "\n".join(rebuilt_lines)

        # FIX 5: Normalize spacing around thematic breaks (---)
        cleaned_content = re.sub(
            r"\s*^\s*-{3,}\s*$\s*", r"\n\n---\n\n", cleaned_content, flags=re.MULTILINE
        )

        # ##################################################################
        # --- ANCHOR ID FIXES ([[id]]) ---
        # ##################################################################

        # NEW FIX: Specifically targets and cleans up multi-line passthrough anchors.
        # Example: ++ \n [[++prelim_reqs++]] \n +
        # Becomes: [[prelim_reqs]]
        cleaned_content = re.sub(
            r"^\s*\+\+\s*\n\s*\[\[\+\+(.+?)\+\+\]\]\s*\n\s*\+\s*$",
            r"[[\1]]",
            cleaned_content,
            flags=re.MULTILINE,
        )

        # Ensure anchors are on their own lines for proper parsing.
        cleaned_content = re.sub(r"([^\n])(\[\[.+?\]\])", r"\1\n\2", cleaned_content)
        cleaned_content = re.sub(r"(\[\[.+?\]\])([^\n])", r"\1\n\2", cleaned_content)

        # FIX 7: Ensure a blank line between a closing delimiter and a block anchor
        cleaned_content = re.sub(
            r"(--\s*\n)(\[\[.+?\]\])", r"\1\n\2", cleaned_content, flags=re.MULTILINE
        )
        # ##################################################################

        # --- CRITICAL FIX: Ensure exactly one space after list markers (. or ..) ---
        cleaned_content = re.sub(
            r"^((\.{1,2}))\s*(?=\S)", r"\1 ", cleaned_content, flags=re.MULTILINE
        )

        # --- Final Cleanup ---
        cleaned_content = re.sub(r"\n{3,}", r"\n\n", cleaned_content)
        return cleaned_content.strip()

    except Exception as e:
        log_func(
            f"    ERROR: Failed to apply in-memory cleanup logic.\n    Details: {e}"
        )
        return adoc_content_string  # Return original content if cleanup fails


# This part allows the script to be run from the command line for testing.
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python cleanup.py <InputFilePath> [OutputFilePath]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file

    if not os.path.exists(input_file):
        print(f"Error: Input file not found: {input_file}")
        sys.exit(1)

    with open(input_file, "r", encoding="utf-8") as f:
        original_content = f.read()

    print(f"Cleaning file: {input_file}")
    cleaned_text = cleanup_adoc_string(original_content)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(cleaned_text)

    print(f"Cleaned content saved to: {output_file}")
