import os
import sys
import subprocess
import glob
import tkinter as tk
from tkinter import scrolledtext, font, filedialog, messagebox
from tkinter import ttk  # Import ttk for themed widgets
import threading
import re
import shutil


# --- Helper to locate bundled resources (works for PyInstaller + dev) ---
def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    if hasattr(sys, "_MEIPASS"):  # Running inside PyInstaller bundle
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)


# --- Configuration: Ruby scripts are bundled in 'Ruby' folder ---
RUBY_CONVERTER_SCRIPT_STANDARD = resource_path(os.path.join("Ruby", "s1000d1.rb"))
RUBY_CONVERTER_SCRIPT_FAULT = resource_path(os.path.join("Ruby", "s1000d2.rb"))
RUBY_CONVERTER_SCRIPT_SCHED = resource_path(os.path.join("Ruby", "s1000d_sched.rb"))
# Define path for the Lua filter
LUA_FILTER_PATH = resource_path(os.path.join("Ruby", "s1000d_styles.lua"))

# --- LUA FILTER CONTENT (FINAL, CORRECTED VERSION) ---
LUA_FILTER_CONTENT = """
-- Pandoc Lua filter for S1000D Style Conversion
-- Mappings:
-- 1. Text formatted as Italics (Emph) -> AsciiDoc Cross-Reference <<ref>>
-- 2. Text formatted as Bold (Strong) -> AsciiDoc Anchor [[id]]
-- 3. Word Style 'List Number' -> AsciiDoc List (Level 1, . )
-- 4. Word Style 'List Number 2' -> AsciiDoc List (Level 2, .. )

-- Function to convert Emphasis element (Cross-Reference)
function Emph(el)
  local content_text = pandoc.utils.stringify(el.content)
  return pandoc.RawInline("asciidoc", "<<" .. content_text .. ">>")
end

-- Function to convert Strong element (Cross-Reference)
function Strong(el)
  local content_text = pandoc.utils.stringify(el.content)
  return pandoc.RawInline("asciidoc", "[[" .. content_text .. "]]")
end

-- CRITICAL FIX: The ListItem function now directly modifies its content
-- by prepending the correct AsciiDoc marker based on its custom style.
function ListItem(el)
  local style_name = el.attributes["custom-style-name"]
  local marker_str = nil
  
  if style_name == "List Number" then
    marker_str = ". "
  elseif style_name == "List Number 2" then 
    marker_str = ".. "
  end
  
  if marker_str then
    -- Ensure the list item has content (e.g., a paragraph)
    if #el.content > 0 then
      local first_block = el.content[1]
      
      -- If it's a Plain or Para block (most common for list items)
      if first_block.tag == "Plain" or first_block.tag == "Para" then
        -- Create new inlines by prepending the marker
        local new_inlines = pandoc.Inlines{pandoc.Str(marker_str)}
        
        -- Append the original content of the first block
        for _, inline_el in ipairs(first_block.content) do
          table.insert(new_inlines, inline_el)
        end
        -- Replace the first block with a new Plain block containing the marked content
        el.content[1] = pandoc.Plain(new_inlines)
      end
    end
    
    -- Return the modified ListItem. It has its marker directly injected.
    return el
  end
  
  -- If no custom style, let Pandoc handle it normally
  return nil
end

-- The OrderedList function is TEMPORARILY REMOVED to isolate the "nil value" error.
-- We will address [arabic] attributes in Python cleanup if necessary.
-- function OrderedList(el)
--   el.attributes = pandoc.Attr()
--   return el
-- end

-- BulletList function is no longer needed for custom-styled lists,
-- as ListItem directly handles the marking.
"""
# --- END LUA FILTER CONTENT ---
# ----------------------------------------------------------------------
# --- BACKEND CONVERSION LOGIC ---
# ----------------------------------------------------------------------


def cleanup_adoc_string(adoc_content_string, log_func):
    """
    Applies general cleanup and fixes to the generated AsciiDoc content (in-memory string),
    reversing the over-aggressive list insertion and fixing step attributes.
    """
    log_func(f"    Applying in-memory cleanup logic...")
    try:
        content = adoc_content_string

        # --- Structural Cleanup ---

        # 1. FIX: Remove isolated, empty AsciiDoc section headers (e.g., '== \n *')
        cleaned_content = re.sub(r"^\s*=+?\s*$", r"", content, flags=re.MULTILINE)

        # 2. FIX: Remove unwanted soft line breaks ('+') generated by Pandoc
        cleaned_content = re.sub(r",\s*\n\s*\+\s*\n", r",\n", cleaned_content)
        cleaned_content = re.sub(r"([^\n,])\n\s*\+\s*\n", r"\1\n", cleaned_content)
        cleaned_content = re.sub(
            r"(.+?)\s*\+\s*$", r"\1", cleaned_content, flags=re.MULTILINE
        )

        # --- FIX: Reversing over-aggressive list insertion (dots everywhere) ---

        # 3. CRITICAL FIX: Remove misplaced dots and unwanted attributes:
        # a) Dots before section headers (e.g., `.==`, `.===`)
        cleaned_content = re.sub(
            r"^\s*\.(\=+)\s+", r"\1 ", cleaned_content, flags=re.MULTILINE
        )

        # b) Dots before list attributes (e.g., `.[arabic]`, `.[start=2]`)
        cleaned_content = re.sub(
            r"^\s*\.(\[.+?\])", r"\1", cleaned_content, flags=re.MULTILINE
        )

        # d) Fix table header marker issue
        cleaned_content = re.sub(
            r"^\s*\.\|===", r"|===", cleaned_content, flags=re.MULTILINE
        )

        # e) NEW FIX: Remove [arabic] or [arabic, start=X] attributes (as requested)
        cleaned_content = re.sub(
            r"\[arabic(\s*,\s*start=\d+)?\]\s*",
            r"",
            cleaned_content,
            flags=re.MULTILINE,
        )

        # This secondary fix catches any standalone dot on a line that should be part of the following list content
        cleaned_content = re.sub(
            r"^\s*\.\s*$\n([A-Z0-9\[].*)", r". \1", cleaned_content, flags=re.MULTILINE
        )

        # The sub-steps also need to be cleaned of extra dots/spaces if they lose their parent attribute
        cleaned_content = re.sub(
            r"^\s*\.\s+Sub-step", r".. Sub-step", cleaned_content, flags=re.MULTILINE
        )

        # --- General Cleanup (Final pass for previously working fixes) ---
        cleaned_content = re.sub(
            r"\{\s*empty\s*\}", r"", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*\{plus\}\s*$", r"+", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(
            r"^\s*____\s*$", r"", cleaned_content, flags=re.MULTILINE
        )
        cleaned_content = re.sub(r"(--\n)\s+", r"\1", cleaned_content)
        cleaned_content = re.sub(r"\s+(\n--)", r"\1", cleaned_content)

        # --- CROSS-REFERENCE FIXES (<<ref>>) ---
        cleaned_content = re.sub(r"<<\s*(.+?)\s*>>", r"<<\1>>", cleaned_content)
        cleaned_content = re.sub(
            r"<<(.*)([\.\,\?\!\:\;])>>", r"<<\1>>\2", cleaned_content
        )

        # FIX 4: Join multi-line attribute blocks `[...]` into a single line
        lines = cleaned_content.splitlines()
        rebuilt_lines = []
        in_attribute_block = False
        for line in lines:
            stripped_line = line.strip()
            if stripped_line.startswith("[") and not stripped_line.endswith("]"):
                in_attribute_block = True
                rebuilt_lines.append(line.rstrip())
            elif in_attribute_block:
                rebuilt_lines[-1] += " " + stripped_line.replace("`", "")
                if stripped_line.endswith("]"):
                    in_attribute_block = False
            else:
                rebuilt_lines.append(line)
        cleaned_content = "\n".join(rebuilt_lines)

        # FIX 5: Normalize spacing around thematic breaks (---)
        cleaned_content = re.sub(
            r"\s*^\s*-{3,}\s*$\s*", r"\n\n---\n\n", cleaned_content, flags=re.MULTILINE
        )

        # --- ANCHOR ID FIXES ([[id]]) ---
        cleaned_content = re.sub(r"([^\n])(\[\[.+?\]\])", r"\1\n\2", cleaned_content)

        # FIX 7: Ensure a blank line between a closing delimiter and a block anchor
        cleaned_content = re.sub(
            r"(--\s*\n)(\[\[.+?\]\])", r"\1\n\2", cleaned_content, flags=re.MULTILINE
        )

        cleaned_content = re.sub(r"(\[\[.+?\]\])([^\n])", r"\1\n\2", cleaned_content)

        # --- CRITICAL FIX: Ensure exactly one space after list markers (. or ..) ---
        # This is a defensive, late-stage fix to ensure list items always have correct spacing
        # Example: ".Item" becomes ". Item", "..SubItem" becomes ".. SubItem"
        cleaned_content = re.sub(
            r"^((\.{1,2}))\s*(?=\S)",  # Capture one or two dots, then zero or more spaces, followed by non-whitespace
            r"\1 ",  # Replace with captured dots and exactly one space
            cleaned_content,
            flags=re.MULTILINE,
        )

        # --- Final Cleanup ---
        cleaned_content = re.sub(r"\n\s*\n", r"\n\n", cleaned_content)
        return cleaned_content

    except Exception as e:
        log_func(
            f"    ERROR: Failed to apply in-memory cleanup logic.\n    Details: {e}"
        )
        return adoc_content_string  # Return original content if cleanup fails


def process_dmc_filename(filename, log_func):
    """Converts a standardized DMC filename format to a new, structured format."""
    if not filename.startswith("DMC-"):
        return filename

    base_code = filename[4:]
    parts = base_code.split("-")

    if len(parts) == 8:
        p1, p2, p3, p4, p5, p6, p7, p8 = parts
        subSystemCode = p4[0] if len(p4) > 0 else ""
        subSubSystemCode = p4[1] if len(p4) > 1 else ""
        disassyCode = p6[:-1] if len(p6) > 0 else ""
        disassyCodeVariant = p6[-1] if len(p6) > 0 else ""
        infoCode_raw = p7[:-1] if len(p7) > 0 else ""
        infoCodeVariant = p7[-1] if len(p7) > 0 else ""
        infoCode = infoCode_raw.zfill(3)
        final_parts = [
            p1,
            p2,
            p3,
            subSystemCode,
            subSubSystemCode,
            p5,
            disassyCode,
            disassyCodeVariant,
            infoCode,
            infoCodeVariant,
            p8,
        ]
        return "DMC-" + "-".join(final_parts)
    return filename


# Helper function to ensure the Lua filter file exists
def ensure_lua_filter_exists(log_func):
    """Writes the Lua filter content to the expected file path."""
    global LUA_FILTER_PATH, LUA_FILTER_CONTENT

    try:
        os.makedirs(os.path.dirname(LUA_FILTER_PATH), exist_ok=True)
        with open(LUA_FILTER_PATH, "w", encoding="utf-8") as f:
            f.write(LUA_FILTER_CONTENT)
        log_func(
            f"    Info: Lua filter created at '{os.path.basename(LUA_FILTER_PATH)}'."
        )
        return True
    except Exception as e:
        log_func(f"    ERROR: Could not write Lua filter file. Details: {e}")
        return False


def convert_step1(input_dir, log_func, dm_type):
    """
    Step 1: Executes Pandoc with the Lua filter directly on the source DOCX.
    Returns a dictionary of {filename_no_ext: adoc_content_string}.
    """
    log_func(
        "Starting Step 1: Processing source documents (DOCX -> ADOC) using Lua filter..."
    )

    if not ensure_lua_filter_exists(log_func):
        return None  # Indicate failure

    docx_files = glob.glob(os.path.join(input_dir, "*.docx"))
    if not docx_files:
        log_func("  No source documents (.docx) found. Skipping Step 1.")
        return {}  # Return empty dict if no files

    processed_adoc_content = {}

    for docx_file in docx_files:
        filename_with_ext = os.path.basename(docx_file)
        log_func(f'  - Processing: "{filename_with_ext}"')
        filename_no_ext = os.path.splitext(filename_with_ext)[0]

        if filename_no_ext.startswith("~$"):
            log_func("    ...SKIPPED (temporary file).")
            continue

        final_dmc = process_dmc_filename(filename_no_ext, log_func)
        # Placeholder header content
        if dm_type in ("sched", "schedule", "scheduled", "scheduled maintenance"):
            header_content = (
                f":dmc: {final_dmc}\n"
                f":dm-type: sched\n"
                f":tech-name: Sample System Widget Task\n"
                f":dm-title: Scheduled Maintenance Tasks\n"
                f":revdate: 2025-09-02\n"
                f":issue-number: 001\n"
                f":in-work: 00\n"
                f":lang: en\n"
                f":security-classification: 01\n"
                f":responsible-partner-company: EaseYourWork\n"
                f":enterprise-code-rpc: 8910X\n"
                f":originator-enterprise: EaseYourWork\n"
                f":enterprise-code-originator: 8910X\n"
                f":applicability: All applicable units and serial numbers.\n"
                f":brex-dmc: DMC-S1000D-H-041-1-0-0301-00-A-022-A-D\n"
                f":reason-for-update: Initial draft for demonstration purposes.\n\n"
                f"[[prelim_reqs]]\n"
                f"== Preliminary Requirements\n\n"
                f"[[sched_tasks]]\n"
                f"== Scheduled Maintenance Tasks\n"
                f". Perform a general scheduled maintenance check\n"
                f". Inspect and clean critical components\n\n"
            )
        else:
            header_content = f":dmc: {final_dmc}\n:dm-type: {dm_type}\n:tech-name: Sample System Widget Task\n:dm-title: Performing the Widget Calibration Procedure\n:revdate: 2025-09-02\n:issue-number: 001\n:in-work: 00\n:lang: en\n:security-classification: 01\n:responsible-partner-company: EaseYourWork\n:enterprise-code-rpc: 8910X\n:originator-enterprise: EaseYourWork\n:enterprise-code-originator: 8910X\n:applicability: All applicable units and serial numbers.\n:brex-dmc: DMC-S1000D-H-041-1-0-0301-00-A-022-A-D\n:reason-for-update: Initial draft for demonstration purposes.\n\n"

        try:
            # PANDOC COMMAND: Uses Lua filter
            command = [
                "pandoc",
                docx_file,
                "--lua-filter",
                LUA_FILTER_PATH,
                "-t",
                "asciidoc",
            ]

            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=True,
                encoding="utf-8",
                shell=True,
            )
            adoc_content = result.stdout

            # --- Post-Pandoc Cleanup (in memory) ---
            sanitized_content = re.sub(r"\+\+(.*?)\+\+", r"\1", adoc_content)
            sanitized_content = re.sub(
                r"^(\s*image):", r"\1::", sanitized_content, flags=re.MULTILINE
            )

            # Combine header and content, then apply further cleanup
            full_adoc_string = header_content + sanitized_content
            cleaned_content = cleanup_adoc_string(full_adoc_string, log_func)

            processed_adoc_content[filename_no_ext] = cleaned_content

        except FileNotFoundError:
            log_func(
                "\nERROR: Pandoc or other tool was not found. Ensure Pandoc is in your PATH."
            )
            return None
        except subprocess.CalledProcessError as e:
            log_func(
                f"\nERROR: Failed during Pandoc conversion for '{filename_with_ext}'.\n  Details:\n{e.stderr}"
            )
            return None
        except Exception as e:
            log_func(
                f"\nAn unexpected error occurred during Step 1 for '{filename_with_ext}': {e}"
            )
            return None

    return processed_adoc_content


def convert_step2(adoc_contents_dict, final_dir, log_func, dm_type):
    """
    Step 2: Converts in-memory ADOC content to S1000D XML using Asciidoctor and a custom backend.
    """
    log_func("\nStarting Step 2: Generating final S1000D files...")
    os.makedirs(final_dir, exist_ok=True)

    dm_type_key = (dm_type or "").strip().lower()
    if dm_type_key == "fault":
        ruby_script_path = RUBY_CONVERTER_SCRIPT_FAULT
    elif dm_type_key in ("sched", "schedule", "scheduled", "scheduled maintenance"):
        ruby_script_path = RUBY_CONVERTER_SCRIPT_SCHED
    else:
        ruby_script_path = RUBY_CONVERTER_SCRIPT_STANDARD

    if not adoc_contents_dict:
        log_func("  No AsciiDoc content found to process. Skipping Step 2.")
        return True

    if not os.path.exists(ruby_script_path):
        log_func(
            f"ERROR: The required converter script was not found at {ruby_script_path}"
        )
        return False

    for file_name_without_ext, adoc_content_string in adoc_contents_dict.items():
        log_func(
            f"  - Generating from in-memory content for: {file_name_without_ext}.adoc"
        )
        output_file = os.path.join(final_dir, f"{file_name_without_ext}.xml")

        command = [
            "asciidoctor",
            "--trace",
            "-r",
            ruby_script_path,
            "-b",
            "s1000d",
            "-",  # Read from stdin
            "-o",
            output_file,
        ]

        try:
            process = subprocess.run(
                command,
                input=adoc_content_string,  # Pass content to stdin
                check=True,
                capture_output=True,
                text=True,
                encoding="utf-8",
                shell=True,
            )
        except FileNotFoundError:
            log_func(
                "ERROR: Asciidoctor or Ruby not found. Ensure prerequisites are installed."
            )
            return False
        except subprocess.CalledProcessError as e:
            log_func(
                f"ERROR: Failed to generate file from '{file_name_without_ext}.adoc' during Step 2.\n  Details:\n{e.stderr}"
            )
            return False
    return True


# ----------------------------------------------------------------------
# --- TKINTER GUI APPLICATION ---
# ----------------------------------------------------------------------


class ConverterApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("S1000D Conversion Utility")
        self.geometry("850x700")
        self.configure(bg="#E6E6FA")  # Light purple background

        self.input_dir = tk.StringVar()
        self.output_dir = tk.StringVar()
        self.dm_type = tk.StringVar()

        self.is_step1_running = False
        self.is_step2_running = False
        self.loader_chars = ["|", "/", "—", "\\"]
        self.loader_index = 0

        # --- Define Fonts ---
        self.heading_font = font.Font(family="Helvetica", size=14, weight="bold")
        self.button_font = font.Font(family="Helvetica", size=10, weight="bold")
        self.label_font = font.Font(family="Helvetica", size=10)
        self.status_font = font.Font(family="Helvetica", size=11)
        self.status_font_bold = font.Font(family="Helvetica", size=11, weight="bold")
        self.log_font = font.Font(family="Consolas", size=10)  # Monospace for logs

        # --- Define Colors ---
        self.bg_color = "#E6E6FA"  # Lavender
        self.frame_bg = "#FFFFFF"  # White
        self.button_color = "#4682B4"  # SteelBlue
        self.button_active_color = "#5F9EA0"  # CadetBlue
        self.text_color = "#333333"  # Dark Gray

        # --- Status Colors ---
        self.status_pending_fg = "gray"
        self.status_processing_fg = "#FF8C00"  # DarkOrange
        self.status_done_fg = "#228B22"  # ForestGreen
        self.status_failed_fg = "#B22222"  # FireBrick

        # --- TTK Style Configuration ---
        style = ttk.Style()
        style.theme_use("clam")  # A more modern default theme

        style.configure("TFrame", background=self.bg_color)
        style.configure(
            "White.TFrame",
            background=self.frame_bg,
            relief="flat",
            borderwidth=1,
            bordercolor="#DDDDDD",
        )
        style.configure(
            "TLabel",
            background=self.bg_color,
            foreground=self.text_color,
            font=self.label_font,
        )
        style.configure(
            "White.TLabel",
            background=self.frame_bg,
            foreground=self.text_color,
            font=self.label_font,
        )
        style.configure(
            "TButton",
            font=self.button_font,
            background=self.button_color,
            foreground="white",
            padding=6,
            relief="flat",
        )
        style.map(
            "TButton",
            background=[("active", self.button_active_color)],
            foreground=[("active", "white")],
        )

        style.configure(
            "Accent.TButton",  # Style for the main start button
            font=self.heading_font,
            background="#4CAF50",  # Green for main action
            foreground="white",
            padding=10,
            relief="flat",
        )
        style.map(
            "Accent.TButton", background=[("active", "#66BB6A")]
        )  # Lighter green on active

        style.configure(
            "TEntry",
            fieldbackground="white",
            foreground=self.text_color,
            borderwidth=1,
            relief="solid",
        )
        style.configure(
            "TMenubutton",
            background=self.frame_bg,
            foreground=self.text_color,
            font=self.label_font,
            padding=4,
        )
        style.map("TMenubutton", background=[("active", self.button_active_color)])
        style.configure(
            "TScrolledText",
            background="#f8f8f8",
            foreground=self.text_color,
            font=self.log_font,
        )

        # --- Main Frame ---
        main_frame = ttk.Frame(self, padding="15 15 15 15", style="TFrame")
        main_frame.pack(fill=tk.BOTH, expand=True)

        # --- Folder Selection Frame ---
        folder_frame = ttk.Frame(main_frame, padding="10 10", style="White.TFrame")
        folder_frame.pack(fill=tk.X, pady=(0, 20))
        folder_frame.columnconfigure(1, weight=1)

        ttk.Label(
            folder_frame, text="Input Folder (.docx):", style="White.TLabel"
        ).grid(row=0, column=0, padx=(0, 15), pady=5, sticky="w")
        ttk.Button(folder_frame, text="Browse", command=self.select_input_folder).grid(
            row=0, column=2, padx=(5, 0), sticky="ew"
        )
        ttk.Label(
            folder_frame,
            textvariable=self.input_dir,
            relief="solid",
            anchor="w",
            background="white",
            borderwidth=1,
            padding=(5, 5),
        ).grid(row=0, column=1, sticky="ew", ipady=2)

        ttk.Label(folder_frame, text="Output Folder:", style="White.TLabel").grid(
            row=1, column=0, padx=(0, 15), pady=5, sticky="w"
        )
        ttk.Button(folder_frame, text="Browse", command=self.select_output_folder).grid(
            row=1, column=2, padx=(5, 0), sticky="ew"
        )
        ttk.Label(
            folder_frame,
            textvariable=self.output_dir,
            relief="solid",
            anchor="w",
            background="white",
            borderwidth=1,
            padding=(5, 5),
        ).grid(row=1, column=1, sticky="ew", ipady=2)

        # --- DM Type Selection ---
        ttk.Label(folder_frame, text="Select DM Type:", style="White.TLabel").grid(
            row=2, column=0, padx=(0, 15), pady=5, sticky="w"
        )
        DM_TYPE_OPTIONS = ["descript", "procedure", "fault", "sched"]
        self.dm_type.set(DM_TYPE_OPTIONS[0])
        dm_type_menu = ttk.OptionMenu(
            folder_frame,
            self.dm_type,
            DM_TYPE_OPTIONS[0],
            *DM_TYPE_OPTIONS,
            style="TMenubutton",
        )
        dm_type_menu.grid(row=2, column=1, sticky="ew", ipady=2, pady=5)
        dm_type_menu.config(width=20)  # Give the OptionMenu a reasonable width

        # --- Start Conversion Button ---
        self.start_button = ttk.Button(
            main_frame,
            text="Start Full Conversion",
            command=self.start_conversion_thread,
            style="Accent.TButton",
        )
        self.start_button.pack(pady=20, fill=tk.X, ipady=5)

        # --- Progress Status Frame ---
        status_frame = ttk.LabelFrame(
            main_frame, text="Progress", padding="10 10", style="White.TFrame"
        )
        status_frame.pack(fill=tk.X, pady=10)
        status_frame.columnconfigure(2, weight=1)

        self.step1_loader = ttk.Label(
            status_frame,
            text="",
            font=self.status_font_bold,
            width=2,
            background=self.frame_bg,
        )
        self.step1_loader.grid(row=0, column=0, sticky="w", padx=5)
        ttk.Label(
            status_frame,
            text="Step 1: Process Source Documents",
            font=self.status_font,
            background=self.frame_bg,
        ).grid(row=0, column=1, sticky="w", pady=2)
        self.step1_status = ttk.Label(
            status_frame,
            text="Pending",
            font=self.status_font,
            foreground=self.status_pending_fg,
            background=self.frame_bg,
        )
        self.step1_status.grid(row=0, column=2, sticky="e", padx=5)

        self.step2_loader = ttk.Label(
            status_frame,
            text="",
            font=self.status_font_bold,
            width=2,
            background=self.frame_bg,
        )
        self.step2_loader.grid(row=1, column=0, sticky="w", padx=5)
        ttk.Label(
            status_frame,
            text="Step 2: Generate S1000D Files",
            font=self.status_font,
            background=self.frame_bg,
        ).grid(row=1, column=1, sticky="w", pady=2)
        self.step2_status = ttk.Label(
            status_frame,
            text="Pending",
            font=self.status_font,
            foreground=self.status_pending_fg,
            background=self.frame_bg,
        )
        self.step2_status.grid(row=1, column=2, sticky="e", padx=5)

        # --- Detailed Log ---
        ttk.Label(
            main_frame,
            text="Detailed Log:",
            anchor="w",
            font=self.label_font,
            background=self.bg_color,
        ).pack(fill=tk.X, pady=(10, 5))
        self.log_widget = scrolledtext.ScrolledText(
            main_frame,
            wrap=tk.WORD,
            font=self.log_font,
            state=tk.DISABLED,
            bg="#f8f8f8",
            fg=self.text_color,
            relief="solid",
            borderwidth=1,
            padx=5,
            pady=5,
        )
        self.log_widget.pack(pady=5, fill=tk.BOTH, expand=True)

    def select_input_folder(self):
        path = filedialog.askdirectory(title="Select Folder Containing DOCX Files")
        if path:
            self.input_dir.set(path)

    def select_output_folder(self):
        path = filedialog.askdirectory(title="Select a Base Folder for Output")
        if path:
            self.output_dir.set(path)

    def log(self, message):
        self.after(0, self._update_log, message)

    def _update_log(self, message):
        self.log_widget.config(state=tk.NORMAL)
        self.log_widget.insert(tk.END, message + "\n")
        self.log_widget.config(state=tk.DISABLED)
        self.log_widget.see(tk.END)

    def update_status(self, label, text, color):
        self.after(
            0, lambda: label.config(text=text, foreground=color)
        )  # Use foreground for ttk.Label

    def update_loader(self):
        if self.is_step1_running or self.is_step2_running:
            char = self.loader_chars[self.loader_index % len(self.loader_chars)]
            if self.is_step1_running:
                self.step1_loader.config(text=char)
            if self.is_step2_running:
                self.step2_loader.config(text=char)
            self.loader_index += 1
            self.after(100, self.update_loader)

    def run_full_conversion(self):
        self.start_button.config(state=tk.DISABLED)
        self.log_widget.config(state=tk.NORMAL)
        self.log_widget.delete("1.0", tk.END)
        self.log_widget.config(state=tk.DISABLED)

        self.update_status(
            self.step1_status, "Processing...", self.status_processing_fg
        )
        self.update_status(self.step2_status, "Pending", self.status_pending_fg)
        self.step1_loader.config(text="")
        self.step2_loader.config(text="")

        input_path = self.input_dir.get()
        output_path = self.output_dir.get()
        selected_dm_type = self.dm_type.get()

        if not all([input_path, output_path]):
            messagebox.showerror(
                "Error",
                "Please select both an Input and Output folder before starting.",
            )
            self.start_button.config(state=tk.NORMAL)
            return

        final_dir = os.path.join(output_path, "S1000D_Output", "DMs")

        self.is_step1_running = True
        adoc_contents_for_step2 = convert_step1(input_path, self.log, selected_dm_type)
        self.is_step1_running = False
        self.step1_loader.config(text="")

        if adoc_contents_for_step2 is None:
            self.update_status(self.step1_status, "✗ Failed", self.status_failed_fg)
            self.start_button.config(state=tk.NORMAL)
            self.log("\n❌ Process stopped due to failure in Step 1.")
            return

        self.update_status(self.step1_status, "✓ Done", self.status_done_fg)

        self.update_status(
            self.step2_status, "Processing...", self.status_processing_fg
        )
        self.is_step2_running = True
        step2_ok = convert_step2(
            adoc_contents_for_step2, final_dir, self.log, selected_dm_type
        )
        self.is_step2_running = False
        self.step2_loader.config(text="")

        if not step2_ok:
            self.update_status(self.step2_status, "✗ Failed", self.status_failed_fg)
            self.log("\n❌ Process stopped due to failure in Step 2.")
            self.start_button.config(state=tk.NORMAL)
            return
        self.update_status(self.step2_status, "✓ Done", self.status_done_fg)

        self.log(
            "\n----------------------------------------------------------------------"
        )
        self.log("✅ Full conversion process completed successfully!")
        self.log(f"  Final S1000D XML files are in: '{final_dir}'")
        self.log("  No intermediate .adoc files were saved to disk.")
        self.start_button.config(state=tk.NORMAL)

    def start_conversion_thread(self):
        self.start_button.config(state=tk.DISABLED)
        self.is_step1_running, self.is_step2_running = False, False
        self.after(100, self.update_loader)
        threading.Thread(target=self.run_full_conversion, daemon=True).start()


if __name__ == "__main__":
    app = ConverterApp()
    app.mainloop()
